export const STATUS = {
	LOADING: 'LOADING',
	ERROR: 'ERROR',
	READY: 'READY',
	ACTIVE: 'ACTIVE',
	RUNNING: 'RUNNING',
	FINISHED: 'FINISHED',
};

export const ACTION_TYPE = {
	DATA_RECEIVED: 'DATA_RECEIVED',
	DATA_FAILED: 'DATA_FAILED',
	START: 'START',
	NEW_ANSWER: 'NEW_ANSWER',
	NEXT_QUESTION: 'NEXT_QUESTION',
	FINISH: 'FINISH',
	RESTART: 'RESET',
	TICK: 'TICK',
};
